---
apiVersion: v1
kind: Namespace
metadata:
  name: kanarod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-autoscaler
  namespace: default
spec:
  selector:
    matchLabels:
      app: camunda-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: camunda-autoscaler
    spec:
      serviceAccountName: camunda-autoscaler
      containers:
        - name: kanarod
          image: local.registry/camunda-autoscaler:1.0.0
          imagePullPolicy: Always
          env:
            - name: API_PATH
              value: "http://toornament-csgo"
          resources:
            limits:
              cpu: "0.1"
              memory: 128Mi
