---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanarod
  namespace: kanarod
spec:
  selector:
    matchLabels:
      app: kanarod
  replicas: 1
  template:
    metadata:
      labels:
        app: kanarod
    spec:
      containers:
        - name: kanarod
          image: quay.io/jlehtimaki/kanarod
          imagePullPolicy: IfNotPresent
          env:
            - name: API_PATH
              value: "http://toornament-csgo"
          resources:
            limits:
              cpu: "0.1"
              memory: 128Mi