---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanarod
  namespace: kanarod
spec:
  selector:
    matchLabels:
      app: kanarod
  replicas: 1
  template:
    metadata:
      labels:
        app: kanarod
    spec:
      containers:
        - name: kanarod
          image: quay.io/jlehtimaki/kanarod
          imagePullPolicy: IfNotPresent
          env:
            - name: API_PATH
              value: "http://toornament-csgo:8080"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: kanarod
                  key: token
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: access-token
                  name: toornament-csgo
            - name: REDIS_ADDRESS
              value: redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: redis
          resources:
            limits:
              cpu: "0.1"
              memory: 128Mi
